name: getpaper
channels:
  - conda-forge
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - python-dotenv
  - pytorch
  - pdfminer.six
  - pdfplumber
  - jupyterlab #for examples only
  - pip:
      - pydantic==1.10.12
      - pycomfort>=0.0.15
      - click>=8.1.7
      - scidownl
      - pynction
      - twine
      - python-dotenv
      - pycomfort>=0.0.14
      - click
      - pynction
      - langchain>=0.1.0
      - langchain_community>=0.0.11
      - scidownl>=1.0.2
      - Deprecated
      - semanticscholar>=0.5.0
      - PyMuPDF>=1.23.6
      - unpywall>=0.2.2
      - webdriver-manager
      - selenium
