name: getpaper
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - python-dotenv
  - pytorch
  - pdfminer.six
  - pdfplumber
  - jupyterlab #for examples only
  - pip:
      - pycomfort>=0.0.14
      - click>=8.1.7
      - scidownl
      - pynction
      - twine
      - python-dotenv
      - pycomfort>=0.0.14
      - click
      - pynction
      - langchain>=0.0.338
      - scidownl>=1.0.2
      - Deprecated
      - semanticscholar>=0.5.0
      - PyMuPDF>=1.23.6
      - unpywall>=0.2.2
      - webdriver-manager
      - selenium
      - habanero
